##################################################################################
#
#   Virtual SOC with MITRE Attack integration with AWS Security Hub
#
#   Secrets Manager Template:
#     Access Credentials for VSOC MITRE ATT&CK v12 integration database
#
#   See Parameters section for names and descriptions of required parameters.
# 
##################################################################################

AWSTemplateFormatVersion: 2010-09-09
Description: Access Credentials for VSOC MITRE ATT&CK integration database
Metadata: {}

Parameters: 
  DefaultKey: 
    Description: "Default Kms"
    Type: String

Mappings: {}

Conditions: {}

Resources:
  IntegrationMitreReaderSecret:
    Type: AWS::SecretsManager::Secret
    UpdateReplacePolicy: Retain
    DeletionPolicy: Delete
    Properties: 
      Description: Lambda User access credentials to VSOC Mitre Repository
      Name: vsoc-mitreintsh-rds-reader-secret
      SecretString: '{"username":"mirlambdareader","password":"reader12345"}'
      KmsKeyId: !Ref DefaultKey
      Tags: 
        - Key: Name
          Value: 'vsoc-mitreintsh-rds-reader-secret'

Outputs:
  SecretReaderCredentials:
    Description: Lambda User access credentials to VSOC Mitre Integration Repository ARN
    Value: !Ref IntegrationMitreReaderSecret